Update shellstuff

diff --git a/shellstuff b/shellstuff
--- a/shellstuff
+++ b/shellstuff
@@ -12,3 +12,35 @@ case "$1" in
     exit 2
     ;;
 esac
+
+
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+
+
+#!/bin/bash
+# file.sh: a sample shell script to demonstrate the concept of Bash shell functions
+# define usage function
+usage(){
+    echo "Usage: $0 filename"
+    exit 1
+}
+
+# define is_file_exists function
+# $f -> store argument passed to the script
+is_file_exists(){
+    local f="$1"
+    [[ -f "$f" ]] && return 0 || return 1
+}
+# invoke  usage
+# call usage() function if filename not supplied
+[[ $# -eq 0 ]] && usage
+
+# Invoke is_file_exits
+if ( is_file_exists "$1" )
+then
+ echo "File found: $1"
+else
+ echo "File not found: $1"
+fi
+
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
